/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteVisitas.java
 *
 * Created on 13/06/2011, 11:08:39 AM
 */
package tareas;

import controladores.Cliente;
import controladores.RecursosPC;
import java.awt.event.KeyEvent;
import javax.swing.JCheckBox;

/**
 *
 * @author USUARIO
 */
public class ClienteVisitas extends javax.swing.JDialog {

    /** Creates new form ClienteVisitas */
    Cliente c;    
    JCheckBox cajas[];
    public ClienteVisitas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
           setLocation((int)RecursosPC.getAncho()/2-getWidth()/2, (int)RecursosPC.getAlto()/2-getHeight()/2);
        cajas = new JCheckBox[]{lun,mar,mier,juev,vier,sab,dom};
        c = new Cliente();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lun = new javax.swing.JCheckBox();
        mier = new javax.swing.JCheckBox();
        mar = new javax.swing.JCheckBox();
        juev = new javax.swing.JCheckBox();
        sab = new javax.swing.JCheckBox();
        vier = new javax.swing.JCheckBox();
        dom = new javax.swing.JCheckBox();
        asignar_btn = new javax.swing.JButton();
        salir_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Cliente ID:");

        id_cliente.setToolTipText("Presione \"Enter\" para buscar");
        id_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                id_clienteKeyPressed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Frecuentar los siguientes dias"));

        lun.setText("LUN");

        mier.setText("MIE");

        mar.setText("MAR");

        juev.setText("JUE");

        sab.setText("SAB");

        vier.setText("VIE");

        dom.setText("DOM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(juev)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dom)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dom)
                    .addComponent(sab)
                    .addComponent(vier)
                    .addComponent(juev)
                    .addComponent(mier)
                    .addComponent(mar)
                    .addComponent(lun))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        asignar_btn.setText("Asignar");
        asignar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignar_btnActionPerformed(evt);
            }
        });

        salir_btn.setText("Salir");
        salir_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(asignar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 229, Short.MAX_VALUE)
                        .addComponent(salir_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asignar_btn)
                    .addComponent(salir_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asignar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignar_btnActionPerformed
       codigoFrecuencia(); 
        c.setFrecuentado(frec);
        c.actualizarCliente();
        
    }//GEN-LAST:event_asignar_btnActionPerformed

    private void id_clienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_clienteKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
          if(!id_cliente.getText().equals("")){
              c.setID(Integer.parseInt(id_cliente.getText()));
              if(c.buscarClientePorID()){
                 nombre.setText(c.getNombre());
                  frec = c.getFrecuentado();
                 frecuencia();
              }
           }
        }
    }//GEN-LAST:event_id_clienteKeyPressed

    private void salir_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir_btnActionPerformed
        dispose();
    }//GEN-LAST:event_salir_btnActionPerformed

    int aux=0;
    String frec;
    void frecuencia(){        
       for(aux=0; aux<frec.length(); aux++){
          if(frec.substring(aux, aux+1).equals("1")){
            cajas[aux].setSelected(true);
          }
       }
    }
    
    void codigoFrecuencia(){
        frec="";
      for(aux=0; aux<7; aux++){          
          if(cajas[aux].isSelected())
            frec+="1";
          else
            frec+="0";
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignar_btn;
    private javax.swing.JCheckBox dom;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox juev;
    private javax.swing.JCheckBox lun;
    private javax.swing.JCheckBox mar;
    private javax.swing.JCheckBox mier;
    private javax.swing.JLabel nombre;
    private javax.swing.JCheckBox sab;
    private javax.swing.JButton salir_btn;
    private javax.swing.JCheckBox vier;
    // End of variables declaration//GEN-END:variables
}
