/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ValeCarga.java
 *
 * Created on 7/06/2011, 09:57:35 AM
 */
package tareas;

import controladores.RecursosPC;
import controladores.Rutas;
import java.awt.Frame;
import reportes.Intervalo;
import reportes.ReportesClass;

/**
 *
 * @author USUARIO
 */
public class SeleccionRuta extends javax.swing.JDialog {

    /** Creates new form ValeCarga */
    Rutas r;
    ReportesClass rep;
    Intervalo i;
    Frame parental;
    
    public SeleccionRuta(java.awt.Frame parent, boolean modal, ReportesClass reporte, Intervalo ii) {
        super(parent, modal);
        initComponents();
        parental = parent;
        setLocation((int)RecursosPC.getAncho()/2-getWidth()/2, (int)RecursosPC.getAlto()/2-getHeight()/2);
        r = new Rutas();
        rep = reporte;        
        i = ii;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        combo_rutas = new javax.swing.JComboBox();
        responsable = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cancelar_btn = new javax.swing.JButton();
        generar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vale de carga");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel12.setText("Ruta:");

        combo_rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_rutasActionPerformed(evt);
            }
        });

        responsable.setEditable(false);

        jLabel1.setText("Responsable:");

        cancelar_btn.setText("Cancelar");
        cancelar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_btnActionPerformed(evt);
            }
        });

        generar_btn.setText("Generar");
        generar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_rutas, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(generar_btn)
                            .addGap(18, 18, 18)
                            .addComponent(cancelar_btn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(responsable, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(combo_rutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(responsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generar_btn)
                    .addComponent(cancelar_btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_rutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_rutasActionPerformed
        r.setIdRuta(combo_rutas.getSelectedIndex()+1);
        responsable.setText(r.getResponsable());
}//GEN-LAST:event_combo_rutasActionPerformed

    private void cancelar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_btnActionPerformed
        setVisible(false);
}//GEN-LAST:event_cancelar_btnActionPerformed

    private void generar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_btnActionPerformed
        rep.setParametro("ID_RUTA", combo_rutas.getSelectedIndex()+1);
        rep.setParametro("NOM_EMP", responsable.getText());
        rep.setParametro("NOM_RUTA", combo_rutas.getSelectedItem().toString());
        setVisible(false);
        i.setVisible(true);
        //r.desconectar();
}//GEN-LAST:event_generar_btnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        r.getRutas(combo_rutas);        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //r.desconectar();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JComboBox combo_rutas;
    private javax.swing.JButton generar_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JTextField responsable;
    // End of variables declaration//GEN-END:variables
}
